### ISSUE TITLE
Is't possible to use it on Android platform?

### ISSUE THREAD

**Issue by willard-yuan** [FALCONN-LIB/FALCONN#49]
The library of FALCONN only depends on Eigen, and the Eigen has [Android version](https://android.googlesource.com/platform/external/eigen/). Is't possible to use it on Android platform?

**Comment by ludwigschmidt** [comment]
We haven't tested FALCONN on Android ourselves, but it looks like the Android version you linked to is based on a fairly recent version of Eigen (3.2.2):

https://android.googlesource.com/platform/external/eigen/+/master/README.android

We currently include the beta version of Eigen 3.3 in FALCONN because Eigen 3.3 can utilize AVX. But most Android platforms probably don't support AVX, so using Eigen 3.2 should not have negative performance impact there.

Our wiki has instructions for pointing FALCONN to a specific version of Eigen: https://github.com/FALCONN-LIB/FALCONN/wiki/Installation-and-Compiler-Setup

If you get a chance to try FALCONN on Android, let us know how it goes!
